<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\Exceptions\FindItemInMemoryException.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Дополнение к ДЗ8\Otus.ToDoList.ConsoleBot\Otus.ToDoList.ConsoleBot.csproj" />
  </ItemGroup>

</Project>
